import { UserActions } from "../../datatypes/userDataTypes";

export const ActionTypes: UserActions = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

    // For User
    GET_ALL_USERS: "GET_ALL_USERS",
    REGISTER_USER: "REGISTER_USER",
    REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
    LOGIN_USER: "LOGIN_USER",
    LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
    USER_DETAILS: "USER_DETAILS",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
    DELETE_USER: "DELETE_USER",
    LOGOUT_USER: "LOGOUT_USER",
  };

